import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed-variant": "#434750",
        "on-tertiary": "#2c3039",
        primary: "#ffd597",
        "surface-variant": "#32353c",
        "inverse-on-surface": "#2e3037",
        background: "#10131a",
        "tertiary-fixed-dim": "#c3c6d1",
        outline: "#9f8e78",
        "on-primary": "#432c00",
        "on-surface-variant": "#d7c4ac",
        "on-surface": "#e1e2eb",
        "surface-container": "#1d2026",
        surface: "#10131a",
        "on-primary-container": "#6a4700",
        "on-secondary": "#68000b",
        "on-primary-fixed": "#281800",
        "error-container": "#93000a",
        "surface-container-high": "#272a31",
        "on-secondary-container": "#ffb8b2",
        "on-secondary-fixed": "#410004",
        "on-primary-fixed-variant": "#614000",
        error: "#ffb4ab",
        "surface-tint": "#ffba43",
        "inverse-surface": "#e1e2eb",
        tertiary: "#d8dbe6",
        "on-error-container": "#ffdad6",
        "on-tertiary-fixed": "#181c24",
        "on-error": "#690005",
        "primary-fixed": "#ffddaf",
        "on-secondary-fixed-variant": "#930014",
        "surface-dim": "#10131a",
        secondary: "#ffb3ae",
        "surface-container-highest": "#32353c",
        "secondary-fixed": "#ffdad7",
        "tertiary-container": "#bcbfca",
        "primary-fixed-dim": "#ffba43",
        "on-background": "#e1e2eb",
        "surface-bright": "#363940",
        "on-tertiary-container": "#4a4e57",
        "secondary-container": "#ad031a",
        "surface-container-lowest": "#0b0e14",
        "secondary-fixed-dim": "#ffb3ae",
        "outline-variant": "#524533",
        "tertiary-fixed": "#dfe2ee",
        "surface-container-low": "#191c22",
        "inverse-primary": "#805600",
        "primary-container": "#ffb000",
      },
      fontFamily: {
        headline: ["'Space Grotesk'", "sans-serif"],
        body: ["'Inter'", "sans-serif"],
        label: ["'Inter'", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0px",
        lg: "0px",
        xl: "0px",
        full: "9999px",
      },
    },
  },
  plugins: [],
};

export default config;
